version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9.0-stretch
    steps:
      - run: sudo apt-get update && sudo apt-get -y install git curl
      - checkout
      - run: bash -c "$(curl -fsSL motohidentaku.com/dot)"
#  test:
#    docker:
#      - image: circleci/<language>:<version TAG>
#    steps:
#      - checkout
#      - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
#      - test
